#!/bin/sh

docker run --rm -it --net=host -v $PWD/scripts:/opt/scripts -v /home/ratzzo/.local/share/TerrariaServer:/root/.local/share/Terraria ratzzo/terraria-server 
#-v /opt/valheim-world:/home/steam/.config/unity3d/IronGate/Valheim ratzzo/valheim-server
#wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-1432.zip
#unzip terraria-server-1432.zip
