#!/bin/sh

cpu=arm
magic='\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00'
mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
qemu=/usr/bin/qemu-arm-static
binfmt_register=/proc/sys/fs/binfmt_misc/register

if [ "$1" == "register" ]
then
    if [ -f $binfmt_register ]
    then
        echo ":qemu-$cpu:M::$magic:$mask:$qemu:$flags" > $binfmt_register
    else
        exit 1
    fi
elif [ "$1" == "unregister" ]
then
    if [ -f /proc/sys/fs/binfmt_misc/qemu-$cpu ]
    then
        echo -1 > /proc/sys/fs/binfmt_misc/qemu-$cpu
    fi
fi


