FROM ratzzo/alpine-openrc:latest

RUN	apk add --no-cache	nginx			\
						php7-fpm		\ 
						php7			\
						php7-opcache	\
						php7-zip		\
						php7-phalcon	\
						php7-memcached	\
						memcached		\
						php7-pdo		\
						php7-pdo_sqlite	\
						sqlite			\
						rsyslog     
