#boilerplate stuff
FROM ${MULTICONTAINER_BUILD_INHERIT_IMAGE}

#append old setup to setup chain
#only passing redefined variables
#inherited variables are kept
RUN touch /opt/setup_chain && \
    echo DOCKER_IMAGE=$DOCKER_IMAGE >> /opt/setup_chain && \
    echo DOCKER_SETUP=$DOCKER_SETUP >> /opt/setup_chain && \
    echo DOCKER_EP=$DOCKER_EP >> /opt/setup_chain && \
    echo ${DOCKER_SETUP} >> /opt/setup_chain && \
    chmod +x /opt/setup_chain || true

## real docker stuff ##

#add repos and packages
RUN	echo -e "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
	apk add --no-cache openrc openssh sudo rsync

## end real docker stuff ##
	
#more boilerplate
ENV DOCKER_IMAGE=${MULTICONTAINER_BUILD_IMAGE}
ENV DOCKER_SETUP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup
ENV DOCKER_EP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/entrypoint
ADD scripts /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts

## real docker stuff ##

RUN mkdir -p /run/openrc && \
    touch /run/openrc/softlevel && \
    echo > /etc/init.d/hwdrivers && \
    echo > /etc/init.d/networking && \
    echo > /etc/init.d/cgroups && \
    rc-status

ADD scripts/openrc-run.sh /lib/rc/sh/openrc-run.sh

## end real docker stuff ##

ENTRYPOINT sh -c "/opt/setup_chain; cd $(dirname $DOCKER_EP); $DOCKER_EP"
