#boilerplate stuff
FROM ${MULTICONTAINER_BUILD_INHERIT_IMAGE}

#append old setup to setup chain
#only passing redefined variables
#inherited variables are kept
RUN touch /opt/setup_chain && \
    echo DOCKER_IMAGE=$DOCKER_IMAGE >> /opt/setup_chain && \
    echo DOCKER_SETUP=$DOCKER_SETUP >> /opt/setup_chain && \
    echo DOCKER_EP=$DOCKER_EP >> /opt/setup_chain && \
    echo ${DOCKER_SETUP} >> /opt/setup_chain && \
    chmod +x /opt/setup_chain || true
    
ENV DOCKER_IMAGE=${MULTICONTAINER_BUILD_IMAGE}
ENV DOCKER_SETUP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup
ENV DOCKER_EP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/entrypoint

## real docker stuff ##

RUN	apk add --no-cache shadow nginx mariadb mariadb-client php82 php82-fpm php82-curl \
    php82-enchant php82-gd php82-iconv php82-imap php82-intl php82-ldap php82-mysqli php82-odbc \
    php82-opcache php82-pdo_mysql php82-pdo_sqlite php82-soap php82-sockets php82-sqlite3 php82-zip \
    php82-session php82-json php82-phar php82-openssl php82-pear php82-dev php82-mbstring gcc musl-dev g++ make openssl-dev php82-dom
RUN touch /run/openrc/started/networking /run/openrc/started/machine-id && pear update-channels

#setup pear and install openswoole
#enable coroutine sockets? [no] : y
#enable openssl support? [no] : y
#enable http2 protocol? [no] : y
#enable coroutine mysqlnd? [no] : n
#enable coroutine curl? [no] : y
#enable coroutine postgres? [no] : n

RUN echo -en "y\ny\ny\nn\ny\nn\n" | pecl install openswoole
RUN pecl install igbinary
RUN apk add --no-cache tzdata rsyslog php82-pcntl php82-posix
RUN apk add --no-cache clang llvm ninja cmake musl-dev binutils gcc g++ wabt file python3 wasi-sdk lld imagemagick tesseract-ocr ghostscript cronie epoch nano miller gzip xz xz-dev php82-xdebug php82-ffi

## end real docker stuff ##

ADD scripts /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts

#run build time setup script
RUN /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup building

## real docker stuff ##



## end real docker stuff ##

ENTRYPOINT sh -c "/opt/setup_chain; cd $(dirname $DOCKER_EP); $DOCKER_EP"
