#!/usr/bin/perl

#env vars
#EXTLINUX_TIMEOUT
#EXTLINUX_PROMPT
#EXTLINUX_DEFAULT
#EXTLINUX_LABEL
#EXTLINUX_KERNEL
#EXTLINUX_INITRD
#EXTLINUX_FDTDIR
#EXTLINUX_APPEND

$ENV{'EXTLINUX_KERNEL_NAME'}	= "UNKNOWN_KERNEL"									if(!$ENV{'EXTLINUX_KERNEL_NAME'});
$ENV{'EXTLINUX_TIMEOUT'}		= 20												if(!$ENV{'EXTLINUX_TIMEOUT'});
$ENV{'EXTLINUX_PROMPT'}			= 1													if(!$ENV{'EXTLINUX_PROMPT'});
$ENV{'EXTLINUX_DEFAULT'}		= $ENV{'EXTLINUX_KERNEL_NAME'}						if(!$ENV{'EXTLINUX_DEFAULT'});
$ENV{'EXTLINUX_LABEL'}			= $ENV{'EXTLINUX_DEFAULT'}							if(!$ENV{'EXTLINUX_LABEL'});
$ENV{'EXTLINUX_MENU_LABEL'}		= $ENV{'EXTLINUX_DEFAULT'}							if(!$ENV{'EXTLINUX_MENU_LABEL'});
$ENV{'EXTLINUX_KERNEL'}			= "/boot/zImage-$ENV{'EXTLINUX_KERNEL_NAME'}"		if(!$ENV{'EXTLINUX_KERNEL'});
$ENV{'EXTLINUX_INITRD'}			= "/boot/initramfs-$ENV{'EXTLINUX_KERNEL_NAME'}"	if(!$ENV{'EXTLINUX_INITRD'});
$ENV{'EXTLINUX_FDTDIR'}			= "/boot/dtbs-$ENV{'EXTLINUX_KERNEL_NAME'}"			if(!$ENV{'EXTLINUX_FDTDIR'});
$ENV{'EXTLINUX_APPEND'}			= "modules=loop,squashfs,sd-mod,usb-storage bootmedia=/dev/mmcblk0p1 overlaytmpfs=yes root=/media/mmcblk0p1/rootfs.ext4" if(!$ENV{'EXTLINUX_APPEND'});

print <<EOF;
TIMEOUT $ENV{'EXTLINUX_TIMEOUT'}  
PROMPT $ENV{'EXTLINUX_PROMPT'}   
DEFAULT $ENV{'EXTLINUX_DEFAULT'} 

LABEL $ENV{'EXTLINUX_LABEL'} 
MENU LABEL $ENV{'EXTLINUX_KERNEL_NAME'}  
KERNEL $ENV{'EXTLINUX_KERNEL'}
INITRD $ENV{'EXTLINUX_INITRD'}
FDTDIR $ENV{'EXTLINUX_FDTDIR'}
APPEND $ENV{'EXTLINUX_APPEND'}
EOF
