#boilerplate stuff
FROM ${MULTICONTAINER_BUILD_INHERIT_IMAGE}

#append old setup to setup chain
#only passing redefined variables
#inherited variables are kept
RUN touch /opt/setup_chain && \
    echo DOCKER_IMAGE=$DOCKER_IMAGE >> /opt/setup_chain && \
    echo DOCKER_SETUP=$DOCKER_SETUP >> /opt/setup_chain && \
    echo DOCKER_EP=$DOCKER_EP >> /opt/setup_chain && \
    echo ${DOCKER_SETUP} >> /opt/setup_chain && \
    chmod +x /opt/setup_chain || true
    
ENV DOCKER_IMAGE=${MULTICONTAINER_BUILD_IMAGE}
ENV DOCKER_SETUP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup
ENV DOCKER_EP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/entrypoint

## real docker stuff ##

RUN	apk add --no-cache shadow nginx mariadb mariadb-client php83 php83-fpm php83-curl \
    php83-enchant php83-gd php83-iconv php83-imap php83-intl php83-ldap php83-mysqli php83-odbc \
    php83-opcache php83-pdo_mysql php83-pdo_sqlite php83-soap php83-sockets php83-sqlite3 php83-zip php83-json php83-phar php83-xdebug php83-xmlreader php83-ctype php83-mbstring openssl php83-xml php83-session
RUN touch /run/openrc/started/networking /run/openrc/started/machine-id

## end real docker stuff ##

ADD scripts /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts

#run build time setup script
RUN /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup wordpress
RUN /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup building

## real docker stuff ##



## end real docker stuff ##

ENTRYPOINT sh -c "/opt/setup_chain; cd $(dirname $DOCKER_EP); $DOCKER_EP"
