.PHONY: status run clean

Dockerfile: Dockerfile.in Makefile
	@sed_escape() { echo "$$1" | sed -e 's/[\/&]/\\&/g'; }; sed \
	-e 's/$${MULTICONTAINER_BUILD_INHERIT_IMAGE}/'$$(sed_escape "$(MULTICONTAINER_BUILD_INHERIT_IMAGE)")'/g' \
	-e 's/$${MULTICONTAINER_BUILD_INHERIT_IMAGE_ESCAPED}/'$$(sed_escape "$(MULTICONTAINER_BUILD_INHERIT_IMAGE_ESCAPED)")'/g' \
	-e 's/$${MULTICONTAINER_BUILD_IMAGE}/'$$(sed_escape "$(MULTICONTAINER_BUILD_IMAGE)")'/g' \
	-e 's/$${MULTICONTAINER_BUILD_IMAGE_ESCAPED}/'$$(sed_escape "$(MULTICONTAINER_BUILD_IMAGE_ESCAPED)")'/g' \
	-e 's/$${MULTICONTAINER_IMAGE_NAME}/'$$(sed_escape "$(MULTICONTAINER_IMAGE_NAME)")'/g' \
	$< > $@ || rm -f $@

$(MULTICONTAINER_BUILD_OUTDIR):
	mkdir -p $@
	
$(MULTICONTAINER_BUILD_OUTDIR)/built: Dockerfile $(MULTICONTAINER_BUILD_SCRIPTSDIR) $(MULTICONTAINER_BUILD_DEPENDENCIES_CHECK_TARGETS) | $(MULTICONTAINER_BUILD_OUTDIR)
	DOCKER_BUILDKIT=1 docker build . \
	-t $(MULTICONTAINER_DOCKER_USERNAME)/$(MULTICONTAINER_IMAGE_NAME)
	touch $@

$(MULTICONTAINER_BUILD_DEPCHECK_OUTDIR): | $(MULTICONTAINER_BUILD_OUTDIR)
	mkdir -p $@
	
clean:
	@if [ ! $(MULTICONTAINER_BUILD_OUTDIR) ]; then exit 1; fi;
	rm -rf $(MULTICONTAINER_BUILD_OUTDIR)/*
	
build: $(MULTICONTAINER_BUILD_OUTDIR)/built
	
run:
	$(MULTICONTAINER_QUICK_RUN_COMMAND)

dep_run: $(MULTICONTAINER_BUILD_OUTDIR)/built
	$(MULTICONTAINER_RUN_COMMAND)

status:
	@echo MULTICONTAINER_DOCKER_USERNAME=$(MULTICONTAINER_DOCKER_USERNAME)
	@echo MULTICONTAINER_BASE_DIR=$(MULTICONTAINER_BASE_DIR)
	@echo MULTICONTAINER_WORKING_DIR=$(MULTICONTAINER_WORKING_DIR)
	@echo MULTICONTAINER_IMAGE_NAME=$(MULTICONTAINER_IMAGE_NAME)
	@echo MULTICONTAINER_BUILD_DEPENDENCIES=$(MULTICONTAINER_BUILD_DEPENDENCIES)
	@echo MULTICONTAINER_RUN_COMMAND=$(MULTICONTAINER_RUN_COMMAND)
	@echo MULTICONTAINER_BUILD_INHERIT_IMAGE=$(MULTICONTAINER_BUILD_INHERIT_IMAGE)
	@echo MULTICONTAINER_BUILD_IMAGE=$(MULTICONTAINER_BUILD_IMAGE)
	@echo MULTICONTAINER_BUILD_IMAGE_ESCAPED=$(MULTICONTAINER_BUILD_IMAGE_ESCAPED)
	@echo MULTICONTAINER_BUILD_INHERIT_IMAGE_ESCAPED=$(MULTICONTAINER_BUILD_INHERIT_IMAGE_ESCAPED)
	@echo MULTICONTAINER_BUILD_DEPENDENCIES_EXPANDED=$(MULTICONTAINER_BUILD_DEPENDENCIES_EXPANDED)
	@echo MULTICONTAINER_BUILD_DEPENDENCIES_CHECK_TARGETS=$(MULTICONTAINER_BUILD_DEPENDENCIES_CHECK_TARGETS)

$(MULTICONTAINER_BUILD_DEPCHECK_OUTDIR)/%: $(MULTICONTAINER_BUILD_DEPCHECK_OUTDIR)
	make -C $(MULTICONTAINER_BASE_DIR)/$(notdir $@) build
	touch $@

	
