#!/bin/sh

#runtime setup script

if [ ! "$DOCKER_IMAGE" ]; then exit 1; fi;

CONTAINER_USER=user
USER_HOME=/home/${CONTAINER_USER}
SHARED_ETC=/tmp/shared/etc

#build time part
RELATIVE_SCRIPTS_PATH=$(dirname "$DOCKER_SETUP")
if [ -d "$RELATIVE_SCRIPTS_PATH/persist/etc" ]; then
    cp -r "$RELATIVE_SCRIPTS_PATH/persist/etc" /
fi

#allow user to login and add sudo access
#RANDOM_PASSWORD=$(dd if=/dev/urandom bs=32 count=10 status=none | md5sum | cut -d ' ' -f 1);
#echo -e "${RANDOM_PASSWORD}\n${RANDOM_PASSWORD}\n" | passwd ${CONTAINER_USER} > /dev/null
#echo -e "${CONTAINER_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

mkdir -p $SHARED_ETC

#link shared files to config for persistence
link_shared_config () {
    if [ ! "$1" ] || [ ! "$2" ] || [ ! "$3" ]; then
        echo "Missing param."
        return 1
    fi
    
    LINK_TYPE="$1"
    LOCATION_SHARED="$2" #shared location
    LOCATION_CONTAINER="$3" #location inside the container
    
    if [ "$LINK_TYPE" == "dir" ]; then
        if [ ! -d $LOCATION_SHARED ]; then
            cp -r $LOCATION_CONTAINER $LOCATION_SHARED
        fi
        
        mv $LOCATION_CONTAINER $LOCATION_CONTAINER.old
        ln -s $LOCATION_SHARED $LOCATION_CONTAINER
        
    elif [ "$LINK_TYPE" == "file" ]; then
        if [ ! -f $LOCATION_SHARED ]; then
            cp $LOCATION_CONTAINER $LOCATION_SHARED
        fi
        
        mv $LOCATION_CONTAINER $LOCATION_CONTAINER.old
        ln -s $LOCATION_SHARED $LOCATION_CONTAINER
    else
        echo "not file nor dir"
        return 1
    fi
   
}

link_shared_etc_entry () {
    if [ ! "$1" ]; then return 1; fi;
    ENTRY_NAME="$1"
    ENTRY_TYPE="none"
    if [ -d /etc/$ENTRY_NAME ]; then #directory
        ENTRY_TYPE="dir"
    elif [ -f /etc/$ENTRY_NAME ]; then #file
        ENTRY_TYPE="file"
    fi
    
    link_shared_config $ENTRY_TYPE $SHARED_ETC/$ENTRY_NAME /etc/$ENTRY_NAME
}

#mkdir /etc/bind
#touch /etc/bind/named.conf
link_shared_etc_entry bind


#service dnsmasq start
#/usr/sbin/dnsmasq --keep-in-foreground --pid-file= --conf-file=/etc/dnsmasq.conf



