#!/bin/sh

NGINX_CONF_DEFAULT_SERVER=${NGINX_CONF_DEFAULT_SERVER:-}
NGINX_CONF_SERVE_HTTP=${NGINX_CONF_SERVE_HTTP:-80}
NGINX_CONF_SERVE_HTTPS=${NGINX_CONF_SERVE_HTTPS:-443}
NGINX_CONF_SERVER_NAME=${NGINX_CONF_SERVER_NAME:-}
#fullchain.pem
NGINX_CONF_SSL_CERTIFICATE=${NGINX_CONF_SSL_CERTIFICATE:-}
#privkey.pem
NGINX_CONF_SSL_CERTIFICATE_KEY=${NGINX_CONF_SSL_CERTIFICATE_KEY:-}
NGINX_CONF_SSL_PROTOCOLS=${NGINX_CONF_SSL_PROTOCOLS:-"TLSv1 TLSv1.1 TLSv1.2"}
NGINX_CONF_SSL_CIPHERS=${NGINX_CONF_SSL_CIPHERS:-"ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"}
NGINX_CONF_ROOT=${NGINX_CONF_ROOT:-}
NGINX_CONFIG_NAME=${NGINX_CONF_SERVE_HTTPS:-default.conf}

if [ ! $1 ]
then
    echo "Usage:"
    echo "$0 <config_file>"
    exit 1
fi

if [ "$1" == "reset" ]
then
    rm -f $NGINX_CONFIG_DIRECTORY/*
    echo "Reset."
    exit 0
fi

if  [ "$1" == "generate" ]
then
   echo -en "server {\n"
        if [ ! $NGINX_CONF_SERVE_HTTP -eq 0 ]
        then
            if [ $NGINX_CONF_DEFAULT_SERVER ]
            then
                DEF_SERVER=" default_server"
            else
                DEF_SERVER=
            fi
        echo -en "\tlisten $NGINX_CONF_SERVE_HTTP$DEF_SERVER;\n"
        echo -en "\tlisten [::]:$NGINX_CONF_SERVE_HTTP$DEF_SERVER;\n"
        fi
        
        if [ ! $NGINX_CONF_SERVE_HTTPS -eq 0 ] && [ $NGINX_CONF_SSL_CERTIFICATE ]
        then
            echo -en "\tlisten $NGINX_CONF_SERVE_HTTPS ssl;\n"
            echo -en "\tlisten [::]:$NGINX_CONF_SERVE_HTTPS ssl;\n"
            echo -en "\tssl_certificate $NGINX_CONF_SSL_CERTIFICATE;\n"
            echo -en "\tssl_certificate_key $NGINX_CONF_SSL_CERTIFICATE_KEY;\n"
            echo -en "\tssl_protocols $NGINX_CONF_SSL_PROTOCOLS;\n"
            echo -en "\tssl_ciphers \"$NGINX_CONF_SSL_CIPHERS\";\n"
            echo -en "\tssl on;\n"
        fi
        
        if [ $NGINX_CONF_ROOT ]
        then
            echo -en "\troot $NGINX_CONF_ROOT;\n"
        fi
        
        if [ $NGINX_CONF_SERVER_NAME ]
        then
            echo -en "\tserver_name $NGINX_CONF_SERVER_NAME;\n"
        fi
        
        echo -en "\tlocation / {\n"
        #echo -en "\t\ttry_files \$uri \$uri/;\n"
        echo -en "\t\tdefault_type text/plain;\n"
        echo -en "\t\tautoindex on;\n"
        echo -en "\t}\n"
        
        echo -en "}\n"
        
        
        
#         }
# 
#         # You may need this to prevent return 404 recursion.
#         location = /404.html {
#             internal;
#         }
#     }
#     "

    return 0
fi
