#boilerplate stuff
FROM ${MULTICONTAINER_BUILD_INHERIT_IMAGE}

#append old setup to setup chain
#only passing redefined variables
#inherited variables are kept
RUN touch /opt/setup_chain && \
    echo DOCKER_IMAGE=$DOCKER_IMAGE >> /opt/setup_chain && \
    echo DOCKER_SETUP=$DOCKER_SETUP >> /opt/setup_chain && \
    echo DOCKER_EP=$DOCKER_EP >> /opt/setup_chain && \
    echo ${DOCKER_SETUP} >> /opt/setup_chain && \
    chmod +x /opt/setup_chain || true
    
ENV DOCKER_IMAGE=${MULTICONTAINER_BUILD_IMAGE}
ENV DOCKER_SETUP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/setup
ENV DOCKER_EP=/opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts/entrypoint

## real docker stuff ##

# RUN	echo -e "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
# 	apk add --no-cache openrc openssh sudo

RUN	pacman -Syu --noconfirm
RUN pacman -Sy --noconfirm nodejs yarn
RUN pacman -Sy --noconfirm chromium && yarn global add puppeteer && puppeteer browsers install chrome
RUN pacman -Sy --noconfirm busybox openssh
RUN ssh-keygen -A && ln -s /usr/sbin/busybox /usr/sbin/adduser
RUN pacman -Scc --noconfirm

## end real docker stuff ##

ADD scripts /opt/${MULTICONTAINER_BUILD_IMAGE_ESCAPED}_scripts
ENTRYPOINT sh -c "/opt/setup_chain; cd $(dirname $DOCKER_EP); $DOCKER_EP"
